### ISSUE TITLE
falsy site.title

### ISSUE THREAD

**Issue by cup** [jekyll/github-metadata#146]
With http://github.com/pages-themes/primer, a header shows on every page because
of this code:

~~~html
{% if site.title and site.title != page.title %} 
 <h1><a href="{{ "/" | absolute_url }}">{{ site.title }}</a></h1> 
{% endif %} 
~~~

you should be able to remove under one of these conditions:

1. site.title == page.title
2. site.title == falsy

we dont want to use number 1, as every page would have the same title. for 2, we
should be able to use `nil` or `false`:

http://shopify.github.io/liquid/basics/truthy-and-falsy

however setting `title: nil` or `title: false` in `_config.yml` has no effect.

**Comment by cup** [comment]
https://github.com/jekyll/github-metadata/issues/146
https://github.com/jekyll/jekyll/issues/7387
https://github.com/pages-themes/primer/issues/21

**Comment by ashmaroli** [comment]
@cup I recommend going through the following documentation:
https://github.com/benbalter/jekyll-titles-from-headings#configuration

**Comment by cup** [comment]
@ashmaroli i am choosing to ignore your comment because it is vague

however thanks for your time

cheers

**Comment by cup** [comment]
i found a better hack for this. according to here:

http://github.com/jekyll/github-metadata/blob/6aea65a/lib/jekyll-github-metadata/site_github_munger.rb#L52

if `site.name` is set in `_config.yml`, then `site.title` is not automatically
set, so it will remain "falsy"

so you just need to add `name: hello world` or similar to `_config.yml`

**Comment by ashmaroli** [comment]
> ignore your comment because it is vague

Let me clarify then.
GitHub Pages and their whitelisted themes secondarily fall back to a "truthy" `site.title` or `page.title` by virtue of the plugin [**jekyll-titles-from-headings**](https://github.com/benbalter/jekyll-titles-from-headings)

**Comment by cup** [comment]
@ashmaroli thanks for your continued effort - but simply linking to a repo is not very helpful

perhaps you could list some code to add to `_config.yml` or some similar process to fix the problem - not carefully that i have already found a workaround so you should consider that with any further comments

**Comment by mattr-** [comment]
@cup as you've noted, adding a value for `name` in `_config.yml` with `title` set to `false` prevents the primer theme from rendering the site title on a page. This **is** a fix for the problem. Having the following in your `_config.yml` will prevent the Primer theme from rendering the title:

```yaml
name: true
title: false
```

Unless it's being used somewhere in your site, the value for `name` is inconsequential here, as long as it's not `false` :smiley:

With `_config.yml` being, well, YAML, `false` is the only falsy value that can be used for `title` due to `nil` being interpreted as a normal string by the YAML parser. The normal Liquid parsing rules for falsy values won't apply here since it doesn't come directly from Ruby code.

An alternative approach would be to follow [the layout customization instructions for the theme](https://github.com/pages-themes/primer#layouts) and remove the header rendering code, which will prevent you from having to change your site's config.
